# name: Run Daily Script

# on:
#   schedule:
#     - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
#   workflow_dispatch:      # (Optional) manual trigger from GitHub UI
name: Run Every Minute

# on:
  # schedule:
  #   - cron: '*/1 * * * *'  # Runs every 1 minute
  # workflow_dispatch:        # Allows manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or your required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver


      - name: Run the script
        run: python my_script.py
